### ISSUE TITLE
能在框架中写点注释吗?

### ISSUE THREAD

**Issue by stevesgit** [rocboss/rocphp#2]
hello,想学习下如何写框架，对于开发者和学习者来说，注释总是必不可少的东西吧。

**Comment by rocboss** [comment]
近期将更新的2.2中会有丰富的注释

**Comment by stevesgit** [comment]
@rocboss 恩 ，很期待下次更新。

**Comment by stevesgit** [comment]
@rocboss  具体什么时候能更新呢？ 等了好久。
